/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DentalRouteImport } from './routes/dental'
import { Route as EmployeeRouteRouteImport } from './routes/employee/route'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerRouteRouteImport } from './routes/manager/route'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as ClientLoginRouteImport } from './routes/client/login'
import { Route as DashboardCompaniesRouteImport } from './routes/dashboard.companies'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardPilotsRouteImport } from './routes/dashboard.pilots'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as ManagerHistoryRouteImport } from './routes/manager/history'
import { Route as ManagerSettingsRouteImport } from './routes/manager/settings'
import { Route as ManagerTeamRouteImport } from './routes/manager/team'
import { Route as OwnerDashboardRouteImport } from './routes/owner/dashboard'
import { Route as OwnerLoginRouteImport } from './routes/owner/login'
import { Route as ApiPublicWebhooksVapiRouteImport } from './routes/api/public/webhooks/vapi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalRoute = DentalRouteImport.update({
  id: '/dental',
  path: '/dental',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRouteRoute = EmployeeRouteRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRouteRoute = ManagerRouteRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client/login',
  path: '/client/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCompaniesRoute = DashboardCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPilotsRoute = DashboardPilotsRouteImport.update({
  id: '/pilots',
  path: '/pilots',
  getParentRoute: () => DashboardRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerHistoryRoute = ManagerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerSettingsRoute = ManagerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerTeamRoute = ManagerTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner/dashboard',
  path: '/owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/owner/login',
  path: '/owner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksVapiRoute = ApiPublicWebhooksVapiRouteImport.update({
  id: '/api/public/webhooks/vapi',
  path: '/api/public/webhooks/vapi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/dental': typeof DentalRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trades': typeof TradesRoute
  '/client/login': typeof ClientLoginRoute
  '/dashboard/companies': typeof DashboardCompaniesRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/pilots': typeof DashboardPilotsRoute
  '/manager/history': typeof ManagerHistoryRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/team': typeof ManagerTeamRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/login': typeof OwnerLoginRoute
  '/employee/': typeof EmployeeIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/api/public/webhooks/vapi': typeof ApiPublicWebhooksVapiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/dental': typeof DentalRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trades': typeof TradesRoute
  '/client/login': typeof ClientLoginRoute
  '/dashboard/companies': typeof DashboardCompaniesRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/pilots': typeof DashboardPilotsRoute
  '/manager/history': typeof ManagerHistoryRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/team': typeof ManagerTeamRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/login': typeof OwnerLoginRoute
  '/employee': typeof EmployeeIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/api/public/webhooks/vapi': typeof ApiPublicWebhooksVapiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/dental': typeof DentalRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trades': typeof TradesRoute
  '/client/login': typeof ClientLoginRoute
  '/dashboard/companies': typeof DashboardCompaniesRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/pilots': typeof DashboardPilotsRoute
  '/manager/history': typeof ManagerHistoryRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/team': typeof ManagerTeamRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/login': typeof OwnerLoginRoute
  '/employee/': typeof EmployeeIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/api/public/webhooks/vapi': typeof ApiPublicWebhooksVapiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employee'
    | '/manager'
    | '/dashboard'
    | '/demo'
    | '/dental'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/trades'
    | '/client/login'
    | '/dashboard/companies'
    | '/dashboard/history'
    | '/dashboard/leads'
    | '/dashboard/pilots'
    | '/manager/history'
    | '/manager/settings'
    | '/manager/team'
    | '/owner/dashboard'
    | '/owner/login'
    | '/employee/'
    | '/manager/'
    | '/api/public/webhooks/vapi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/dental'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/trades'
    | '/client/login'
    | '/dashboard/companies'
    | '/dashboard/history'
    | '/dashboard/leads'
    | '/dashboard/pilots'
    | '/manager/history'
    | '/manager/settings'
    | '/manager/team'
    | '/owner/dashboard'
    | '/owner/login'
    | '/employee'
    | '/manager'
    | '/api/public/webhooks/vapi'
  id:
    | '__root__'
    | '/'
    | '/employee'
    | '/manager'
    | '/dashboard'
    | '/demo'
    | '/dental'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/trades'
    | '/client/login'
    | '/dashboard/companies'
    | '/dashboard/history'
    | '/dashboard/leads'
    | '/dashboard/pilots'
    | '/manager/history'
    | '/manager/settings'
    | '/manager/team'
    | '/owner/dashboard'
    | '/owner/login'
    | '/employee/'
    | '/manager/'
    | '/api/public/webhooks/vapi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeeRouteRoute: typeof EmployeeRouteRouteWithChildren
  ManagerRouteRoute: typeof ManagerRouteRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRoute
  DentalRoute: typeof DentalRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TradesRoute: typeof TradesRoute
  ClientLoginRoute: typeof ClientLoginRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerLoginRoute: typeof OwnerLoginRoute
  ApiPublicWebhooksVapiRoute: typeof ApiPublicWebhooksVapiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental': {
      id: '/dental'
      path: '/dental'
      fullPath: '/dental'
      preLoaderRoute: typeof DentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/login': {
      id: '/client/login'
      path: '/client/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/companies': {
      id: '/dashboard/companies'
      path: '/companies'
      fullPath: '/dashboard/companies'
      preLoaderRoute: typeof DashboardCompaniesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pilots': {
      id: '/dashboard/pilots'
      path: '/pilots'
      fullPath: '/dashboard/pilots'
      preLoaderRoute: typeof DashboardPilotsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/history': {
      id: '/manager/history'
      path: '/history'
      fullPath: '/manager/history'
      preLoaderRoute: typeof ManagerHistoryRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/settings': {
      id: '/manager/settings'
      path: '/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof ManagerSettingsRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/team': {
      id: '/manager/team'
      path: '/team'
      fullPath: '/manager/team'
      preLoaderRoute: typeof ManagerTeamRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/login': {
      id: '/owner/login'
      path: '/owner/login'
      fullPath: '/owner/login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/vapi': {
      id: '/api/public/webhooks/vapi'
      path: '/api/public/webhooks/vapi'
      fullPath: '/api/public/webhooks/vapi'
      preLoaderRoute: typeof ApiPublicWebhooksVapiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EmployeeRouteRouteChildren {
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteRouteChildren: EmployeeRouteRouteChildren = {
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteRouteWithChildren = EmployeeRouteRoute._addFileChildren(
  EmployeeRouteRouteChildren,
)

interface ManagerRouteRouteChildren {
  ManagerHistoryRoute: typeof ManagerHistoryRoute
  ManagerSettingsRoute: typeof ManagerSettingsRoute
  ManagerTeamRoute: typeof ManagerTeamRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteRouteChildren: ManagerRouteRouteChildren = {
  ManagerHistoryRoute: ManagerHistoryRoute,
  ManagerSettingsRoute: ManagerSettingsRoute,
  ManagerTeamRoute: ManagerTeamRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteRouteWithChildren = ManagerRouteRoute._addFileChildren(
  ManagerRouteRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCompaniesRoute: typeof DashboardCompaniesRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardPilotsRoute: typeof DashboardPilotsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCompaniesRoute: DashboardCompaniesRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardPilotsRoute: DashboardPilotsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeeRouteRoute: EmployeeRouteRouteWithChildren,
  ManagerRouteRoute: ManagerRouteRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRoute,
  DentalRoute: DentalRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TradesRoute: TradesRoute,
  ClientLoginRoute: ClientLoginRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerLoginRoute: OwnerLoginRoute,
  ApiPublicWebhooksVapiRoute: ApiPublicWebhooksVapiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
